name: CI/CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Run CI from flake.nix
        run: |
          nix flake check

  build_and_release:
    runs-on: ubuntu-22.04
    needs: [check]
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build infra-notify binary
        run: |
          nix build

      - name: Rename infra-notify binary
        run: |
          cp result/bin/infra-notify infra-notify-amd64

      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          files: |
            infra-notify-amd64
